package com.example.mybatisgenerator.mybatis.mapper;

import com.example.mybatisgenerator.mybatis.entity.TestEntity;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long idColumn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insert(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int insertSelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    TestEntity selectByPrimaryKey(Long idColumn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestEntity record);
}